### ISSUE TITLE
[QUESTION] Can I output chemical production and loss rates of NO and NO2  in History.rc

### ISSUE THREAD

**Issue by hongjianweng** [geoschem/GCHP#54] opened 2020-09-28 06:34 UTC
**Ask your question here**
Hi all,

I want to calculate lifetime of NOx and I need the chemical production and loss rates.
I want to add Prod_NO and Loss_NO in History.rc, but it didn't work.
As wiki said, some quantities in ProdLoss  collection are not applicable to certain simulations.
So I wonder whether it can output Prod_NO, Loss_NO, Prod_NO2 and Loss_NO2?

Thanks and waiting for your replying!
Hongjian

**Comment by lizziel** [comment] 2020-10-22 18:47
Hi @hongjianweng, I think this issue is more relevant to GEOS-Chem rather than GCHPctm specifically. It looks like you already created a duplicate of this issue there: https://github.com/geoschem/geos-chem/issues/463. I am therefore closing this issue.

If you tried the suggestion posted on the other issue, add a comment on whether it worked or if you have further questions. We can reopen it if necessary.

**Closed as completed by lizziel** 2020-10-22 18:47 UTC
