### ISSUE TITLE
[BUG/ISSUE] GCHP fails at NetCDF4_get_var.H but doesn't crash

### ISSUE THREAD

**Issue by xpye98** [geoschem/gchp#186] opened 2021-12-03 06:08 UTC
### What institution are you from?
Peking University

### Description of the problem
I noticed that sometimes in slurm output file, there are errors about `NetCDF4_get_var.H` (maybe caused by broken input emission data), but GCHP can still continue to run.
This can be confusing. How does GCHP treat this broken emission in the simulation?

### GEOS-Chem version
v13.2.1

### Description of code modifications
/

### Log files
errors in slurm output are like:
`pe=00018 FAIL at line=00037    NetCDF4_get_var.H                        <status=-101>`

### Software versions
- Compilers (Intel or GNU, and version): gcc@9.3.0
- NetCDF version: netcdf-fortran@4.5.3
- MPI version: intel-mpi
- ESMF version: esmf@8.0.1

**Comment by lizziel** [comment] 2021-12-09 14:12
HI @xpye98, typically if that error is encountered then more information is sent to the log file and the run crashes. For example:

```
 Using parallel NetCDF for file: fvcore_internal_rst
pe=00000 FAIL at line=00037    NetCDF4_get_var.H                        <status=-57>
 Error reading variable          -57
 NetCDF: Start+count exceeds dimension bound

pe=00000 FAIL at line=07253    MAPL_IO.F90                              <status=-57>
pe=00000 FAIL at line=05426    MAPL_IO.F90                              <status=-57>
pe=00000 FAIL at line=01242    MAPL_IO.F90                              <status=-57>
pe=00000 FAIL at line=07392    MAPL_IO.F90                              <status=-57>
pe=00000 FAIL at line=07657    MAPL_IO.F90                              <status=-57>
pe=00000 FAIL at line=05681    MAPL_Generic.F90                         <status=-57>
```

Depending on where the error occurs in GCHP, however, the error may not cause the run to crash due to an issue using the MAPL macro `_VERIFY`. I believe @LiamBindle fixed this in the latest version.

For this particular error the status number returned by `NetCDF4_get_var.H` is the netcdf error code and is not specific to GCHP. A guide to those codes can be found [here](https://www.unidata.ucar.edu/software/netcdf/docs/nc-error-codes.html). For your example the status code is -101 which is defined as "Error at HDF5 layer". This may indicate a problem with the file and you could try opening it outside of running GCHP to check.

Of course that requires knowing what file is the problem, but hopefully that information would be in one of the logs, either the main log or `allPEs.log` (if you haven't already, make sure you maximize prints in `logging.yml` in your debug run by following instructions [here](https://gchp.readthedocs.io/en/latest/supplement/rundir-config.html?highlight=logging.yml#enable-maximum-print-output)). If the variable name is not present in any of the logs then you would need to add code to print it out, such as by adding a print for variable `var_name` in file `src/MAPL/pfio/NetCDF4_get_var.H` if status is non-zero.

Do you have more information on the run that results in this, or can you reproduce it to get the log files? If you could provide that then we can target where error handling could be improved, and submit a fix to the MAPL developers for a future version if one has not already been added. At the very least it would be nice if the code in `NetCDF4_get_var.H` printed the variable name if calling Netcdf function `nf90_get_var` results in a bad value.

**Comment by xpye98** [comment] 2021-12-10 04:50
@lizziel Thanks for you reply!

**Comment by xpye98** [comment] 2021-12-10 05:02
@lizziel Thanks for your reply!

Actually, I found this issue by running gc classic and gchp at the same time. The gc classic will crash with the netcdf error.
It's hard to reproduce the error now since I have replaced the broken emission files, but thanks to your information, now I know the reason.

There is still one concern, that is, what exactly are these bad emissions treated in the model? Maybe just zero value?

**Comment by lizziel** [comment] 2021-12-10 17:27
If MAPL cannot read the variable from file, and the error handling doesn't crash the program, then I'm not sure what value is used. It might be zero, or it might be a garbage number. Do you remember if you did a successful long simulation when getting that error? I suspect it would crash eventually if not initially, just from non-sensical values. Regardless, I believe this issue should be fixed in the latest version since failure in `_VERIFY` should now stop the run. @LiamBindle, can you confirm that issue was fixed?

**Comment by LiamBindle** [comment] 2021-12-15 19:34
@xpye98 Could you share the log file of the simulation that had an error in `NetCDF4_get_var.H` but continued running? Our group often runs into errors here because we have an issue with our file system that causes random I/O errors that manifest as errors in `NetCDF4_get_var.H`. I haven't ever seen a non-fatal error here, and it would be crucial we fix that because it would affect simulation results.

**Comment by lizziel** [comment] 2022-01-03 16:32
@LiamBindle, I am going to close out this issue now. If @xpye98 does not have the log file from the run that crashed then I think we could corrupt an input file to try to reproduce.

**Closed as completed by lizziel** 2022-01-03 16:32 UTC
Labels: category: Bug

**Comment by arifein** [comment] 2022-03-22 18:13
Hello, I am trying to set up the Hg simulation to run on GCHP (v13.3.4) and I ran into the same error discussed here. Running a 3 day test simulation, I get multiple errors like: 
`pe=00022 FAIL at line=00037    NetCDF4_get_var.H                        <status=-57>`
However, doesn't seem to be fatal since the simulation continues for the full 3 days. Since @LiamBindle wrote before that he would be interested in seeing a log file from this case, I post the log files here (allPEs.log is too large for me to upload here but I have it as well). Is there a way to see which variable `NetCDF4_get_var.H` is having trouble reading?

[HEMCO.log.txt](https://github.com/geoschem/GCHP/files/8326862/HEMCO.log.txt)
[slurm-442522.out.txt](https://github.com/geoschem/GCHP/files/8326863/slurm-442522.out.txt)
[gchp.log.txt](https://github.com/geoschem/GCHP/files/8326864/gchp.log.txt)

**Comment by lizziel** [comment] 2022-03-22 21:50
Thanks for reporting this. See my original response for tips on how to see what variable/file is causing the problem, and do let me know if it doesn't make sense.

I'm curious to see what the issue is. I'd like to reproduce it to make sure it's not still an issue in the MAPL version we'll be upgrading to in 14.0.

**Comment by arifein** [comment] 2022-05-03 14:10
Hi @lizziel I had a question about trying to track down which variable/file is causing the problem. I am not very familiar with MAPL and I'm not sure exactly how to do the print statement. What I tried so far is to edit `NetCDF4_get_var.H` to add an extra if/printf statement:
```
     !$omp critical
      status = nf90_inq_varid(this%ncid, name=var_name, varid=varid)
     !$omp end critical

      _VERIFY(status)
     !$omp critical
#if (_RANK == 0)
      status = nf90_get_var(this%ncid, varid, values)
#else
      status = nf90_get_var(this%ncid, varid, values, start, count)
#endif

#if (status == -57 )
      printf("Variable error is %s \n" , var_name)
#endif
```

I tried to include the print statement when status ==-57 (which is the error outputted in the slurm output) and also tried for status != 0. However, in both cases, I don't get any additional output in the log files. I was just wondering if you have any tips for these print statements.

**Comment by lizziel** [comment] 2022-05-09 13:05
HI @arifein, I've always used fortran rather than C to do the print. Try this:
`if ( status == -57 ) print *, "Variable error is ", trim(var_name) `
