### ISSUE TITLE
Transport Budget Diagnostics at surface level for GCHP14.3.1 C180 simulation are all zero

### ISSUE THREAD

**Issue by YanshunLi-washu** [geoschem/gchp#417] opened 2024-06-01 19:13 UTC
### Your name

Yanshun Li

### Your affiliation

WashU

### Please provide a clear and concise description of your question or discussion topic.

Dear Support Team,

Recently I conducted a GCHP v14.3.1 C180 simulation for the year of 2021, and looked at the budget diagnostic outputs for the transport process at the surface level of GCHP.

Surprisingly, I found the transport mass fluxes are zero for all timestamps, PM2.5 species, grids in the simulation. Relevant settings in the HISTORY.rc file are attached, taking SOAS as an example:

  Budget.template:        '%y4%m2%d2_%h2%n2z.nc4',
  Budget.format:          'CFIO',
  Budget.timestampStart:  .true.
  Budget.frequency:       010000
  Budget.duration:        010000
  Budget.mode:            'time-averaged'
  Budget.fields:          'BudgetWetDepLevs1to1_SOAS     ', 'GCHPchem',
                          'BudgetChemistryLevs1to1_SOAS  ', 'GCHPchem',
                          'BudgetConvectionLevs1to1_SOAS ', 'GCHPchem',
                          'BudgetMixingLevs1to1_SOAS     ', 'GCHPchem',
                          'BudgetEmisDryDepLevs1to1_SOAS ', 'GCHPchem',
                          '**BudgetTransportLevs1to1_SOAS**  ', 'GCHPchem',
  
Is this related to some special treatment of horizontal transport/mass fluxes in GCHP? I expect the transport budget to be non-zero.

Thanks,
Yanshun

**Comment by lizziel** [comment] 2024-06-03 20:06
Hi Yanshun, the transport budget diagnostic is never populated for GCHP. It is only relevant for GC-Classic since it is designed to capture changes from tpcore. If there is a transport budget diagnostics in one of the GCHP `HISTORY.rc` templates then this is a bug.

**Comment by lizziel** [comment] 2024-06-03 20:31
Following up on this, I noticed the Budget diagnostics section of the ReadTheDocs repo shared between GC-Classic and GCHP does not indicate Transport is for GC-Classic only. I'll update the docs for the next version release.

**Comment by YanshunLi-washu** [comment] 2024-06-06 00:41
Hi @lizziel Yes, I put 'BudgetTransportLevs1to1_SOAS ', 'GCHPchem', in the HISTORY.rc file and it gave me all zeros. Thanks for clarifying though. 

Besides, in terms of the new feature of level-to-level budget analysis you developed, just like to update to you that I tried putting the below items in HISTORY.rc:
```console
'BudgetWetDepLevs1to1_SOAS ', 'GCHPchem',
'BudgetChemistryLevs1to1_SOAS ', 'GCHPchem',
'BudgetConvectionLevs1to1_SOAS ', 'GCHPchem',
'BudgetMixingLevs1to1_SOAS ', 'GCHPchem',
'BudgetEmisDryDepLevs1to1_SOAS ', 'GCHPchem',
'BudgetTransportLevs1to1_SOAS ', 'GCHPchem',
```
(1) Are they refer to budgets for the surface model level?
(2) The model run successfully with these budget diagnostics. But when I changed these items to *Levs2to2*, the program crashed with unclear errors. Just wondering can we put sth like 'BudgetEmisDryDepLevs2to2_SOAS ', 'GCHPchem', or 'BudgetEmisDryDepLevs3to3_SOAS ', 'GCHPchem', in HISTORY.rc? Or we can only start from level 1.
(3)'BudgetEmisDryDepLevs1to1_SOAS ' has extremely low values with magnitude of several 1.0e-20, do you have any clue why?

Thanks

**Comment by lizziel** [comment] 2024-06-06 14:34
Yes, "1to1" in the budget diagnostic name means it is surface-level only. You should be able to do something like "3to3" and if you can't then there is a bug. I will test it out and follow-up here if there needs to be a fix.

**Comment by lizziel** [comment] 2024-06-10 19:50
@YanshunLi-washu, I have not been able to reproduce problems using Levs2to2. Could you create a new issue for your problem and include all configuration and log files?

I am not sure about the magnitude of the EmisDryDep surface mass flux. You could take a look at the dry deposition and emissions diagnostics to assess if a low value makes sense.

**Comment by lizziel** [comment] 2024-06-10 20:09
Also note that if using non-local PBL mixing then the emissions and dry deposition budget diagnostic will not
capture all emissions and dry deposition fluxes. Are you using non-local PBL mixing? If yes, then emissions and dry deposition tendencies below the PBL are applied within mixing instead. This might explain the low values you are seeing.

**Comment by lizziel** [comment] 2024-06-18 13:55
I will close this issue now as the original issue is resolved. @YanshunLi-washu, please open a new issue if you still cannot use the LevsNtoN budget diagnostic.

**Closed as completed by lizziel** 2024-06-18 13:55 UTC
Labels: TODO: Documentation, topic: Diagnostics, category: Debug Help
