### ISSUE TITLE
[BUG/ISSUE] GCHP 12.9.3 multirun option fails after 1st run [error: cap_restart did not update to different date]

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#67] opened 2020-12-10 17:09 UTC
Hello, 
To get more familiar with the multi-run option, I am trying to split a 3-hour simulation into 3 jobs (GCHP version 12.9.3), following the respective wiki instructions. However, after the first run, the simulation crashes with an error:  cap_restart did not update to different date. Checking the cap_restart file I can see that the file is empty. 
Maybe the problem is that the date of the first job is not written in the cap_restart file and thus the second job cannot start running? Which part of the code is writting the cap_restart file? 

**Compilation commands**
1. make clean_all
2. make build_all

**Run commands**
./gchp.multirun.sh

### Error messages
There are some errors in the slurm file of the first job (attached), and an error in the multirun.log file: 

```
Error: cap_restart did not update to different date
```

### Your GCHP version and runtime environment:
 - GCHPctm version (can be last commit hash): GHCP 12.9.3
 - MPI type and version:  openmpi/icc/3.0.2
 - Fortran cmpiler type and version: ifort 18.0.2 20180210
 - netCDF version: netcdf/4.7.3-openmpi
 - Are you using GCHP "out of the box" (i.e. unmodified): No
   - If you have modified GCHP, please list what was changed: __

### Input and log files to attach
 - input.geos: [input.geos.txt](https://github.com/geoschem/GCHP/files/5674369/input.geos.txt)

 - HEMCO_Config.rc: [HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/5674447/HEMCO_Config.rc.txt)

 - HEMCO.log: [HEMCO.log.txt](https://github.com/geoschem/GCHP/files/5674422/HEMCO.log.txt)

 - ExtData.rc: [ExtData.rc.txt](https://github.com/geoschem/GCHP/files/5674451/ExtData.rc.txt)

 - HISTORY.rc: [HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/5674453/HISTORY.rc.txt)

 - GCHP.rc: [GCHP.rc.txt](https://github.com/geoschem/GCHP/files/5674367/GCHP.rc.txt)

 - GCHP compile log file: [compile.log.txt](https://github.com/geoschem/GCHP/files/5674364/compile.log.txt)

- CAP.rc: [CAP.rc.txt](https://github.com/geoschem/GCHP/files/5674363/CAP.rc.txt)

 - runConfig.sh: [runConfig.sh.txt](https://github.com/geoschem/GCHP/files/5674371/runConfig.sh.txt)

 - GCHP run log file: [multirun.log.txt](https://github.com/geoschem/GCHP/files/5674370/multirun.log.txt)

 - slurm.out or any other error messages from your scheduler: [slurm-512145.err.txt](https://github.com/geoschem/GCHP/files/5674372/slurm-512145.err.txt)
- slurm.error: [slurm-512145.out.txt](https://github.com/geoschem/GCHP/files/5674373/slurm-512145.out.txt)

- gchp.multirun.run: [gchp.multirun.run.txt](https://github.com/geoschem/GCHP/files/5674365/gchp.multirun.run.txt)

- gchp.multitun.sh: [gchp.multirun.sh.txt](https://github.com/geoschem/GCHP/files/5674366/gchp.multirun.sh.txt)

I would appreciate it if you could provide some help to solve my problem. Thank you in advance.
Regards, 
Maria Tsivlidou

**Comment by LiamBindle** [comment] 2020-12-11 19:32
Hi Maria, 

Thanks for writing. I'm not too familiar with the gchp.multirun script, so please bear with me.

To restart a GCHP simulation you need to:
1. Specify the start date and time to restart at in `cap_restart` (by the way, the format is a `YYYYMMDD hhmmss` string, and that's all the file is), and
2. Specify the checkpoint file with initial conditions to restart with `GCHP.rc`

I suspect what gchp.multirun does, is it tries to automate this. 

It looks like `gchp.multirun.run` throws the error that you got here:
```bash
   if [[ "${new_cap_rst}" = "${cap_rst}" || "${new_cap_rst}" = "" ]]; then
      echo " "
      echo "Error: cap_restart did not update to different date!" >> ${multirunlog}
      echo "Cancelling all jobs." >> ${multirunlog}
      cancel_all_jobs
```
(source: https://github.com/geoschem/geos-chem/blob/0d390164f3441816defd05519f28dfde574a1cfa/run/GCHP/runScriptSamples/gchp.multirun.run#L194)

GCHP writes `cap_restart` at the end of the simulation, and it write the end datetime. For example, if your simulation finished at 2020-12-11 13:00:00 `cap_restart` would be
```
20201211 130000
```

----

#### Your case

It looks like in your simulation: 
1. Initially there was no cap_restart (correct)
2. the simulation started running, and 13 minutes later the simulation exited
3. the next segment started. When this segment was starting, it saw that there was no cap_restart and so the script issued the error that you saw

Thanks for including those log files---that helped me piece this together.

I think what happened is your first segment crashed, and so it didn't update cap_restart; then the second segment started, saw that cap_restart wasn't updated, and so it reported the error. I think slurm-512145.err.txt confirms this.

It looks like your first segment crashed during regridding. The traceback suggests something went wrong to do with MPI. Have you ran GCHP without multirun before; if so, what run script did you use, and is there possible a difference in the environment?

**Comment by mtsivlidou** [comment] 2020-12-11 22:38
Hello Liam,

Thank you very much for your answer. 
Yes, I ran GCHP without multirun using the attached script (gchp_nuwa.run.txt). The environment is the same as the one for the multirun option. 

I have tried some tests trying to set up the multirun option but nothing is working. For example, I make one-hour run using the gchp_nuwa.run.txt, and it was completed successfully after 7minutes. Then, I used the gchp.multitun.sh to make the run again, with Num jobs = 1. In this case, the simulation was running for more than 1 hour and it was not successful. 
Then I tried the test I described above (3-hour simulation splitted in 3 jobs) but still it is not working.
I would appreciate it if you have any suggestions on the matter. 
Thank you in advance.

Regards, 
Maria

[gchp_nuwa.run.txt](https://github.com/geoschem/GCHP/files/5681872/gchp_nuwa.run.txt)

**Comment by LiamBindle** [comment] 2020-12-14 16:48
Hi Maria,

That's good to know single segment runs work okay; I suspect the issue is a subtle difference in environment variables (or something similar).

#### Idea 1
In your gchp_nuwa.run I see the following OpenMPI setings are configured
```bash
export OMPI_MCA_btl=openib,self,vader
export OMPI_MCA_mtl=^mxm
export OMPI_MCA_pml=^yalla
```
but in gchp_multirun.run only the following is set
```bash
export OMPI_MCL_btl=openib                # line 162
```

Could you try setting `OMPI_MCA_mtl` and `OMPI_MCA_pml` in your `gchp.multirun.run`, and try rerunning?

#### Idea 2

Also, I see that your multirun job is using 864 cores&mdash;have you ran GCHP on this many cores before? This is a relatively high core count, and MPI tuning becomes increasingly important here (MPI settings configured through environment variables). If you haven't ran single-segment at 864 cores before, I'd suggest trying that first. If you do have a single-segment run on 864 cores that's operational, I'd take a look at the differences in environment variables.

You can see all the environment variables with the `env` command. For example, you could add this line to your single-segment run
```bash
env > single-segment-environment.txt
```
and then add the following line to your multi-segment run:
```bash
env > multi-segment-environment.txt
```
I would put these commands immediately before the `srun` commands so that you capture exactly the environment variables that GCHP is launched with. Then, after you've tried both simulations, diff the two sets of environment variables like so
```console
$ diff single-segment-environment.txt multi-segment-environment.txt
```
The environment variables that are important most likely start with `OMPI_*`.

Let me know what you find,

-Liam

**Comment by mtsivlidou** [comment] 2020-12-15 12:02
Hello Liam,

I applied your first idea and it is working now. Thanks a lot!

I have used  single-segment at 864 cores only for 1-hour simulation tests.
I would like to ask you another question (I am not sure if I should open another issue for this question).

For my project, I need to do a 30-year simulation with monthly output. I used 6 nodes and 36 cores per node which leads to 216 total cores for a single-segment. One-month simulation under these setting (c48/ 2x2.5 resolution) needs ~ 9 hours (real time) which I find rather expensive. 
How many nodes and cores should I use in order to optimize the time that the simulation needs? I was thinking also to change the timestep of chemistry (and trasport) from 600seconds (1200seconds) to 900seconds (1800 sec)

Thank you in advance,
Maria

**Comment by LiamBindle** [comment] 2020-12-15 16:08
Hi Maria,

That's great! I'm glad that worked!

I opened #69 because I think it's likely of interest to a boarder community. Lets continue our discussion there.

I'll close this issue. Feel free to reopen if you run into any more problems.

**Closed as completed** 2020-12-15 16:17 UTC
Labels: category: Bug
