### ISSUE TITLE
[BUG/ISSUE] Segmentation fault when running c180 simulation

### ISSUE THREAD

**Issue by aechristiansen** [geoschem/GCHP#32] opened 2020-07-13 14:59 UTC
Hello, I have been running GCHPctm at c24 with no issue using GEOS-Chem 12.8.2, but I recently wanted to change my simulation resolution to c180 and am running into problems. 

Some info:
-Running on NCAR Casper environment
-I am running on 8 nodes, 288 cores total (but this error persists if I request different numbers of nodes/cores)
-I am using openmpi 4.0.3 and gfortran 8.3.0 compiler

Regardless of the resources I request from my cluster, the simulation crashes at this point in the log file:

```
 MAPL ExtData initialization complete
Mem/Swap Used (MB) at MAPL_Cap:TimeLoop
=  1.919E+05  3.103E+03
 Calling MAPL ExtData Run_
 ExtData Run_: READ_LOOP
 ExtData Run_: ---PopulateBundle
 ExtData Run_: ---CreateCFIO
 ExtData Run_: ---prefetch
```

I don't receive an error message from the code, but I see this message in my SLURM file and find core files in my run directory:

```
[casper15:68225:0:68225] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xffff
fff2d2f75588)
==== backtrace (tid:  68225) ====
```

What might be causing this?

**Comment by lizziel** [comment] 2020-07-13 16:17
Hi @aechristiansen, the issue appears to be during input handling. I will try to reproduce the issue at c180. Could you tell me what tagged version of GCHPctm that you are using? You can do 'git log -n 1' and the tag name should be shown at the top, starting with 13.0.0-alpha.

**Comment by aechristiansen** [comment] 2020-07-13 16:29
Thanks for looking into this. When I do 'git log -n 1' in my run directory, this is what is provided: commit e0710d53790fb89c2b70dcb4d3035de0d05a9108.

**Comment by lizziel** [comment] 2020-07-13 16:45
Your run directory is under different version control than the source code. Change directories to CodeDir from your run directory and then do git log again.

**Comment by aechristiansen** [comment] 2020-07-13 16:49
Ah, sorry about that. From my CodeDir: commit 36265cae14d5d7c52962ce8a75bfadf6959b946f.

**Comment by lizziel** [comment] 2020-07-13 17:06
Thanks! I forgot there was an extra commit on current master for the README. The tag, 13.0.0-alpha.5, is actually the commit just prior so you wouldn't have seen it with git log -n 1.

**Comment by lizziel** [comment] 2020-07-14 16:21
Following up, my run is still waiting in our very busy cluster queue so I haven't yet been able to test c180 with alpha.5 yet. In the meantime, if you have the resources available, I suggest the following:

1) Rebuild GCHPctm using debug flags. You can do this by including -DCMAKE_BUILD_TYPE=Debug during the cmake configure step. You do not need to rebuild ESMF.

2) Run with 384 cores, and make sure you have at least 8G available per core for the run. This is a conservative limit based on the old GCHP. The dev version, which has a new MAPL library, may be more efficient, but it is has not been tested yet. For my system which has 128G per node, and 32 cores per node, I configure resources to use only 16 cores per node and 24 nodes total to get 384 cores.

3) Set your run for 1 hour only and turn on ExtData debug prints. You can do this by enabling the debug option in runConfig.sh.

Let me know how it goes. You can drag and drop you log file (with extension .txt added) into the github comment box directly to share it.

**Comment by aechristiansen** [comment] 2020-07-14 18:40
Thanks for the update! My cluster is down today for scheduled maintenance, but I'll try your suggestions tomorrow when it's back up and running. I'll let you know how it goes.

**Comment by aechristiansen** [comment] 2020-07-17 21:17
Sorry for the delay in my response -- my cluster ended up being down longer than planned. I've rebuilt GCHPctm using debug flags, and the output from that is attached here in case that is helpful. I set up a run to use 384 cores with ExtData debug prints on, and it's sitting in the queue, where I suspect it will be for a bit.
[gchpctm_build_debug.pdf](https://github.com/geoschem/GCHPctm/files/4940335/gchpctm_build_debug.pdf)

**Comment by lizziel** [comment] 2020-07-20 13:48
The log file appears to only contain output for the configure step. This sets up the makefiles to build but does not actually recompile. Did you also do make -j and copy the executable to the run directory before submitting your run?

**Comment by aechristiansen** [comment] 2020-07-20 15:50
Yes, I did make -j and copied the executable before submitting the run. Sorry I forgot to include that! I have attached my output from the make command in the "gchpctm_geos" file.

Also, my run finally ran this morning, and crashed after a couple minutes. I have a different error this time than previously, where I did not hit a segmentation fault, but rather seem to have run into a problem in MAPL_AbstractRegridder.F90. I've attached the GCHP log file (gchptest_log) and my slurm output (gchptest_slurm).

[gchptest_log.txt](https://github.com/geoschem/GCHPctm/files/4948708/gchptest_log.txt)
[gchptest_slurm.txt](https://github.com/geoschem/GCHPctm/files/4948713/gchptest_slurm.txt)
[gchpctm_geos.pdf](https://github.com/geoschem/GCHPctm/files/4948649/gchpctm_geos.pdf)

**Comment by lizziel** [comment] 2020-07-20 16:18
Hmm, the issue is clearly in MAPL: 
```
 ExtData Run_: ---PopulateBundle
 ExtData Run_: ---CreateCFIO
 ExtData Run_: ---prefetch
 create_route_handle        1450
 initialize_subclass        1309
 MAPL_RegridderManager_private::make_regridder_from_grids         269
```
GCHPctm 13.0.0-alpha.5 uses an older version of MAPL than what NASA GMAO is currently using, and I wonder if there was a bug. I still haven't gotten my c180 run to complete due to cluster issues so I have not been able to verify. Because GCHPctm 13.0 is still in development we need to focus on the latest dev branch, which now has MAPL 2.2.7, rather than debug older dev versions that have older MAPL. High resolution testing of GCHPctm will be occurring over the next several weeks.

If you urgently need a fix you could create an issue with the MAPL developers at https://github.com/GEOS-ESM/MAPL. Searching for the error message I found one GitHub issue with it, but it did not really shed light on what the cause is, nor seems directly applicable to your use case: https://github.com/GEOS-ESM/MAPL/issues/170.

Alternatively you could wait until 13.0.0 development and testing is further along.

**Comment by aechristiansen** [comment] 2020-07-21 14:06
Thanks, I'll plan to make an issue with the MAPL developers. Of course, please let me know if you find anything else in your c180 run.

**Comment by lizziel** [comment] 2020-10-21 21:04
Hi @aechristiansen, do you have any updates on this issue?

**Comment by LiamBindle** [comment] 2020-12-18 15:52
Hi @aechristiansen, is it okay if I close this issue?

**Comment by aechristiansen** [comment] 2020-12-18 23:31
Yes, go ahead and close.

**Closed as completed** 2020-12-21 15:10 UTC
